### ISSUE TITLE
Does not work with Ubuntu 20.04 Gnome shell 3.36

### ISSUE THREAD

**Issue by ahsanhussain** [ethanwharris/gnome-nvidia-extension#172]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [check] I am running the latest version
- [check] I checked the documentation and found no answer
- [check] I checked to make sure that this issue has not already been filed

# Expected Behavior

Extension should run

# Current Behavior
Installing from web shows Error. make install from repo doesn't show the extension on browser as well as the tweak tool

**Comment by ethanwharris** [comment]
Hi, thanks for the issue.

The extension is working for me on Ubuntu 20.04, Gnome 3.36. I've uploaded the working version to extensions.gnome.org, but this can take a few weeks / months to become publicly available. In the mean time, double check that you followed the install steps given [here](https://github.com/ethanwharris/gnome-nvidia-extension#installation-from-git), including restarting the gnome-shell. Otherwise I'll post here once the new version is available on gnome-shell.

**Comment by ethanwharris** [comment]
Hi,

The new version of the extension is now up on extensions.gnome.org, so it should be working now :)
