### ISSUE TITLE
Crash when running.

### ISSUE THREAD

**Issue by lahtis** [ethanwharris/gnome-nvidia-extension#198]
# Prerequisites
nvidia-settings 470.57.01-0ubuntu0.18.04.1 (installed)

building and installing in source code. (https://github.com/ethanwharris/gnome-nvidia-extension)

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Current Behavior

TypeError: ExtensionUtils.getSettings is not a function

Stack trace:
  init@/home/tuomas/.local/share/gnome-shell/extensions/nvidiautil@ethanwharris/prefs.js:74:14
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43

What is the current behavior?

not working anymore,. Rebooting computer, not work.

[System]
OS:              Ubuntu 18.04 Bionic Beaver
Arch:            x86_64
Kernel:          5.4.0-104-generic
Desktop:         ubuntu:GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Phenom(tm) II X4 965 Processor
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             7.8 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 770/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 470.103.01
OpenGL Core:     4.6.0 NVIDIA 470.103.01
OpenGL ES:       OpenGL ES 3.2 NVIDIA 470.103.01
Vulkan:          Supported

**Comment by lahtis** [comment]
Main branch. Gnome 3.28.2

**Comment by lahtis** [comment]
Version 6, working.  version 8 not.

**Comment by derenv** [comment]
I think that the way to get the GSettings schema changed at some point during or after Gnome 3.30...

release tag v6 (and v8) uses:

`const Me = ExtensionUtils.getCurrentExtension();`
`const Util = Me.imports.util;`

and

`settings = Util.getSettings();`

while the main branch uses:

`const ExtensionUtils = imports.misc.extensionUtils;`

and

`settings = ExtensionUtils.getSettings();`

this is likely due to the changes we made to the main branch for v9 for Gnome 40 compatibility. there may be a solution [here](https://github.com/negesti/gnome-shell-extensions-negesti/blob/develop/utils.js), i'll make a patch to include in v9 (which is currently in the process of being released).

For now, is v6 working correctly for you? if not, the v8 release tag uses the same method as v6, you could try the v8 release rather than the main branch?

**Comment by lahtis** [comment]
Leave it in the new version. I use the old 6 version when it works. But soon I'll have to upgrade to the new LTS version anyway.

**Comment by lahtis** [comment]
no version 8  not working. Only working settings window, but not show anything else. I cant get any error  messages.

**Comment by derenv** [comment]
so after investigating a bit, i'd suggest sticking with v6 until you upgrade to the next LTS (given that EOL for 18.04 is only later this year) - after fixing the issue there's a bunch more issues with various GJS components. Sadly this is just the nature of gnome extensions, due to gnome updates breaking backwards-compatibility with almost every version. Fortunately 22.04 uses Gnome 3.36.9, and the main branch appears to be compatible with that.
